### ISSUE TITLE
Format of PUT to /add?

### ISSUE THREAD

**Issue by cbleeker** [MystK/node-southwest-automatic-check-in#2]
Hello - it looks like you're taking some params as a PUT to set a new Cron job for the next check-in event.  Can you share the format of this, or do you have a webform you've created to allow PUT'ing these flights in, or do you just use Postman to enter all your flights? :)  If this API to SW is still working, I'd be happy to wrap some UI components to the backend API you've created.

Seen here:

.put('/add', async ctx => {
    try {
      var count = 0
      let body = ctx.request.body
      let time = `55 ${body.time} *`
      delete body.time

**Comment by MystK** [comment]
Yes everything is still working great. :) Thank you for offering! Let met grab the body data from Postman.

**Comment by MystK** [comment]
Looks like the history in my postman is wiped, but it should be something like this.

```
{
  "time": " A B C D",
  "firstName": "E",
  "lastName": "F",
  "confirmationNumber": "G"
}
```
A = Minutes
B = Hours in 24 hour format
C = Day of the month
D = Month
E = First Name
F = Last Name
G = Confirmation Number

Everything except for time is passed onto the Southwest website.

In the code, the email(mines) is hard coded, but it should be a parameter.
